openapi: 3.0.1
info:
  title: API de Transferencia Bancaria
  description: MVP para transferencias entre cuentas dentro del mismo banco.
  version: 1.0.0

servers:
  - url: http://localhost:8080/api

paths:
  /transferencia:
    post:
      summary: Ejecuta una transferencia interna
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferenciaRequest'
      responses:
        '200':
          description: Transferencia exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferenciaResponse'
        '404':
          description: Cuenta origen o destino no existe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                cuentaOrigenNoExiste:
                  summary: Cuenta origen no encontrada
                  value:
                    message: "La cuenta origen no existe"
                cuentaDestinoNoExiste:
                  summary: Cuenta destino no encontrada
                  value:
                    message: "La cuenta destino no existe"
        '422':
          description: La solicitud no pudo ser procesada (e.g. saldo insuficiente)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                saldoInsuficiente:
                  summary: Fondos insuficientes
                  value:
                    message: "Saldo insuficiente en la cuenta origen"

  /cuenta/{cuenta}/saldo:
    get:
      summary: Consulta el saldo de una cuenta
      parameters:
        - name: cuenta
          in: path
          required: true
          schema:
            type: string
          example: "00123456786190"
      responses:
        '200':
          description: Saldo actual
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsultaSaldoResponse'
        '404':
          description: Cuenta no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /transferencia/{cuenta}:
    get:
      summary: Consulta las transferencias de una cuenta
      parameters:
        - name: cuenta
          in: path
          required: true
          schema:
            type: string
          example: "00123456786190"
      responses:
        '200':
          description: Detalles de la transferencia
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransferenciaItem'
        '404':
          description: Cuenta no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    TransferenciaRequest:
      type: object
      required:
        - cuentaOrigen
        - cuentaDestino
        - monto
        - moneda
      properties:
        cuentaOrigen:
          type: string
          example: "00123456786190"
        cuentaDestino:
          type: string
          example: "00123456799999"
        monto:
          type: number
          example: 150.5
        moneda:
          type: string
          example: "PEN"
        descripcion:
          type: string
          example: "Pago de servicios"

    TransferenciaResponse:
      type: object
      properties:
        idTransferencia:
          type: integer
          example: 1
        estado:
          type: string
          example: "EXITOSA"
        fecha:
          type: string
          example: "2025-06-02"

    ConsultaSaldoResponse:
      type: object
      properties:
        cuenta:
          type: string
          example: "00123456786190"
        saldo:
          type: number
          example: 349.5
        moneda:
          type: string
          example: "PEN"

    TransferenciaItem:
      type: object
      properties:
        idTransferencia:
          type: integer
          example: 1
        cuentaOrigen:
          type: string
          example: "00123456786190"
        cuentaDestino:
          type: string
          example: "00123456799999"
        estado:
          type: string
          example: "EXITOSA"
        monto:
          type: number
          example: 150.5
        fecha:
          type: string
          example: "2025-06-02"
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "La cuenta no existe"
